stages:
  - test
  - deploy

# Test Stage
test_services:
  stage: test
  image: node:14 # Assuming you're testing with Node.js

  # Test and install dependencies for admin service
  admin_test:
    script:
      - cd latest_ranthambore/admin
      - npm install
      - npm test

  # Test and install dependencies for chambal service
  chambal_test:
    script:
      - cd latest_ranthambore/chambal
      - npm install
      - npm test

  # Test and install dependencies for client-api-gateway service
  client_api_gateway_test:
    script:
      - cd latest_ranthambore/client/api-gateway
      - npm install
      - npm test
  client_frontend_test:
    script:
      - cd latest_ranthambore/client/frontend
      - npm install
      - npm test      

  client_hotel_test:
    script:
      - cd latest_ranthambore/hotel
      - npm install
      - npm test

  client_package_test:
    script:
      - cd latest_ranthambore/package
      - npm install
      - npm test

  client_payment_test:
    script:
      - cd latest_ranthambore/payment
      - npm install
      - npm test

  client_safari_test:
    script:
      - cd latest_ranthambore/safari
      - npm install
      - npm test

stages:
  - deploy
# Deploy Stage
deploy_services:
  stage: deploy
  image: bash:devel-alpine3.19
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/admin && git pull'
    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/admin && npm install'
    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/admin && pm2 restart admin2'

    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/chambal && npm install'
    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/chambal && pm2 restart chambal2'

    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/client-api-gateway && npm install'
    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/client-api-gateway && pm2 restart api2'

    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/client/frontend && npm install'
    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/client/frontend && pm2 restart frontend2'

    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/hotel && npm install'
    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/hotel && pm2 restart hotel2'

    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/package && npm install'
    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/package && pm2 restart package2'

    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/payment && npm install'
    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/payment && pm2 restart payment2'

    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/safari && npm install'
    - ssh latestranthambore@3.110.148.246 'cd latest_ranthambore/safari && pm2 restart safari2'

  only:
    - main  # Or whichever branch you want to deploy
  dependencies:
    - test_services
<<<<<<< HEAD
=======

>>>>>>> c45966f (ci-cd)
