stages:
  - deploy

# Deploy Stage
deploy_services:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /updated package.json and package-lock.json/ || $CI_COMMIT_MESSAGE =~ /deploy/'
      when: never 
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
    - when: never
  image: bash:devel-alpine3.19
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - |
      ssh latestranthambore@3.110.148.246 << 'EOF'
        cd latest_ranthambore/admin && git pull && npm install && pm2 restart admin2 &
        cd latest_ranthambore/chambal && git pull && npm install && pm2 restart chambal2 &
        cd latest_ranthambore/client-api-gateway && git pull && npm install && pm2 restart api2 &
        cd latest_ranthambore/client/frontend && git pull && npm install && pm2 restart frontend2 &
        cd latest_ranthambore/hotel && git pull && npm install && pm2 restart hotel2 &
        cd latest_ranthambore/package && git pull && npm install && pm2 restart package2 &
        cd latest_ranthambore/payment && git pull && npm install && pm2 restart payment2 &
        cd latest_ranthambore/safari && git pull && npm install && pm2 restart safari2 &
        wait
      EOF
<<<<<<< HEAD
=======

>>>>>>> d6fb48c (ci-cd addition2)
