stages:
  - deploy
  - build
before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: 38.242.196.238
  script:
    - ssh root@38.242.196.238 "cd ranthambore/ && git checkout main && git pull origin main && exit"
  only:
    - main

build_staging:
  stage: build
  environment:
    name: staging
    url: 38.242.196.238
  script:
    - ssh root@38.242.196.238 "cd ranthambore/ && docker -up build && exit"
  when: manual
  only:
    - main