stages:
  - test
  - deploy
  - build
admin:
  image: gitlab.n2rtechnologies.com:5050/arsh/ranthambore/admin
  stage: test
  services:
    - mongo:latest
  script:
    - npm i npm@latest -g
    - npm i
    - npm test
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'

chambal:
  image: gitlab.n2rtechnologies.com:5050/arsh/ranthambore/chambal
  stage: test
  services:
    - mongo:latest
  script:
    - npm i npm@latest -g
    - npm i
    - npm test
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'

hotel:
  image: gitlab.n2rtechnologies.com:5050/arsh/ranthambore/hotel
  stage: test
  services:
    - mongo:latest
  script:
    - npm i npm@latest -g
    - npm i
    - npm test
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'

package:
  image: gitlab.n2rtechnologies.com:5050/arsh/ranthambore/package
  stage: test
  services:
    - mongo:latest
  script:
    - npm i npm@latest -g
    - npm i
    - npm test
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'

payment:
  image: gitlab.n2rtechnologies.com:5050/arsh/ranthambore/payment
  stage: test
  services:
    - mongo:latest
  script:
    - npm i npm@latest -g
    - npm i
    - npm test
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'

safari:
  image: gitlab.n2rtechnologies.com:5050/arsh/ranthambore/safari
  stage: test
  services:
    - mongo:latest
  script:
    - npm i npm@latest -g
    - npm i
    - npm test
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: 38.242.196.238
  script:
    - ssh root@38.242.196.238 "cd ranthambore/ && git checkout main && git pull origin main && exit"
  only:
    - main

build_staging:
  stage: build
  environment:
    name: staging
    url: 38.242.196.238
  script:
    - ssh root@38.242.196.238 "cd ranthambore/ && docker-compose up --build -d"
  when: manual
  only:
    - main