stages:
  - deploy

# Deploy Stage
deploy_services:
  stage: deploy
  rules:
    - if: '$TRIGGER_PIPELINE == "true"'
      when: always
    - if: '$CI_COMMIT_MESSAGE =~ /updated package.json and package-lock.json/ || $CI_COMMIT_MESSAGE =~ /deploy/'
      when: never 
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
    - when: never
  image: bash:devel-alpine3.19
  before_script:
    - apk add --no-cache openssh sshpass
    # Copy the SSH private key to a temporary file
    - echo "$SSH_PRIVATE_KEY" > /tmp/id_rsa
    # Set appropriate permissions on the private key file
    - chmod 600 /tmp/id_rsa

  script:
    - ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no latestranthambore@3.110.148.246 "cd latest_ranthambore && git pull && cd latest_ranthambore/admin && npm i && pm2 restart admin2" 
    - ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no latestranthambore@3.110.148.246 "cd latest_ranthambore/chambal && npm i && pm2 restart chambal2"
    - ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no latestranthambore@3.110.148.246 "cd latest_ranthambore/client-api-gateway && npm i && pm2 restart api2" 
    - ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no latestranthambore@3.110.148.246 "cd latest_ranthambore/client/frontend && npm i && pm2 restart frontend2"
    - ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no latestranthambore@3.110.148.246 "cd latest_ranthambore/hotel && npm i && pm2 restart hotel2"
    - ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no latestranthambore@3.110.148.246 "cd latest_ranthambore/package && npm i && pm2 restart package2"
    - ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no latestranthambore@3.110.148.246 "cd latest_ranthambore/payment && npm i && pm2 restart payment2"
    - ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no latestranthambore@3.110.148.246 "cd latest_ranthambore/safari && npm i && pm2 restart safari2"

